# Generated by Django 4.2.13 on 2024-05-22 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_companycontact_portfolio_delete_galleryimage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='pictures/')),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(choices=[('top_main', 'Top Main Page'), ('middle_main', 'Middle Main Page'), ('about_us', 'About Us Page'), ('services_top', 'Services Top Page')], default='top_main', max_length=20)),
            ],
        ),
    ]
