# Generated by Django 4.2.13 on 2024-05-22 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_pagepicture_delete_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companycontact',
            name='telegram',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='companycontact',
            name='whatsapp',
            field=models.CharField(max_length=20),
        ),
    ]
